# The URL the site will be built for
base_url = "https://saunoja.jp"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

default_language = "ja"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = ["*.dataurl", "*.jpg"]

[languages.fi]
code = "fi"

[languages.ja]
code = "ja"

generate_feed = true

[languages.fi.translations]
catchcopy = "Suomipariskunta blogaa saunasta"
author = "Kirjoittaja"
read_more = "(Lue lisää)"
site-description = "Suomipariskunta blogaa saunasta"
site-url = "https://saunoja.jp/fi"
earlier = "Aiempi kirjoitus: "
later = "Myöhempi kirjoitus: "
open-quote = '"'
close-quote = '"'

[languages.ja.translations]
catchcopy = "フィンランド夫婦は<br>サウナからお届けします"
author = "著者"
read_more = "（続きを読む）"
site-description = "フィンランド夫婦はサウナからお届けします"
site-url = "https://saunoja.jp"
earlier = "前の記事"
later = "後の記事"
open-quote = '【'
close-quote = '】'

[extra]
# Put all your custom variables here
author = 'Pyry & Noora'
site_title = 'SAUNOJA（サウノ屋）'