[[redirects]]
  from = "https://saunoya.jp/*"
  to = "https://saunoja.jp/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.saunoya.jp/*"
  to = "https://saunoja.jp/:splat"
  status = 301
  force = true

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=300"