[[redirects]]
  from = "https://saunoya.jp/*"
  to = "https://saunoja.jp/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.saunoya.jp/*"
  to = "https://saunoja.jp/:splat"
  status = 301
  force = true
